#cloud-config
package_update: true
package_upgrade: true

packages:
  - python3-dev
  - gcc
  - libpq-dev

runcmd:
  - |
    set -e
    mkdir /app
    cd /app
    export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    sudo wget \
       https://dvc.org/deb/dvc.list \
       -O /etc/apt/sources.list.d/dvc.list
    wget -qO - https://dvc.org/deb/iterative.asc | gpg --dearmor > packages.iterative.gpg
    sudo install -o root -g root -m 644 packages.iterative.gpg /etc/apt/trusted.gpg.d/
    rm -f packages.iterative.gpg
    sudo apt update
    sudo apt install dvc -y
    git clone https://github.com/donielix/car-cost-prediction.git
    cd car-cost-prediction/
    dvc pull model
    docker build -t citroen-cost-prediction .
    docker run -d --name citroen-cost-prediction -p 8000:8000 -v model/:/code/model/:ro citroen-cost-prediction
