version: "3.9"

services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - pg_data_mlflow:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mlflow
      POSTGRES_USER: mlflow
      POSTGRES_DB: mlflowdb
      PGPORT: 5432
    ports:
      - 5432:5432

volumes:
  pg_data_mlflow:
